---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Load secrets vault file, if we have one.
    include_vars:
      file: secrets.yml
      name: loop_data
    failed_when: false
  - name: Transfer run.json to secrets.json
    copy:
      dest: secrets.json
      src: run.json
      remote_src: no
  - name: Replace tokens with secrets
    replace:
      path: secrets.json
      regexp: '^(.*)\${{ item.key }}(.*)$'
      replace: '\g<1>{{ item.value }}\g<2>'
    loop: "{{ loop_data | default({}) | dict2items }}"
    loop_control:
      label: "{{ item.key }}"